[package]
name = "parcela"
version = "0.1.3"
edition = "2021"

[dependencies]
aes-gcm = "0.10"
argon2 = "0.5"
clap = { version = "4.5", features = ["derive"] }
lazy_static = "1.4"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
